{
 "title": "Average sensor metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(machineId) (sensor_stats{metricType=\"TEMPERATURE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by(machineId) (sensor_stats{metricType=\"PRESSURE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vibration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by(machineId) (sensor_stats{metricType=\"VIBRATION\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}